name: Publish Artifacts

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  publish:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'matt-ramotar/storex' }}
    runs-on: macos-latest

    strategy:
      matrix:
        module-config:
          - name: "resilience"
            version_env: "RESILIENCE_VERSION_NAME"
            path: ":resilience"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Set Version Environment Variables
        run: |
          RESILIENCE_VERSION=$(grep "^RESILIENCE_VERSION_NAME=" gradle.properties | cut -d'=' -f2)
          echo "RESILIENCE_VERSION_NAME=$RESILIENCE_VERSION" >> $GITHUB_ENV          

      - name: Publish Artifacts to Maven Central
        if: ${{ !endsWith(env[matrix.module-config.version_env], '-SNAPSHOT') }}
        run: ./gradlew ${{ matrix.module-config.path }}:publishAndReleaseToMavenCentral --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
